name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
        mysql-versions: ['5.7', '8.0']
    services:
      mysql:
        image: mysql:${{ matrix.mysql-versions }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: composer:v2, wp-cli

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install WordPress
        run: |
          wp core download --allow-root
          wp config create --allow-root --dbname=wordpress_test --dbuser=root --dbhost=127.0.0.1
          wp core install --allow-root --url=localhost --title="WooCommerce Test" --admin_user=admin --admin_password=admin --admin_email=test@example.com

      - name: Install WooCommerce
        run: |
          wp plugin install woocommerce --allow-root --activate

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit
